//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.11 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2016.10.25 at 11:10:15 AM CEST 
//


package com.qpark.eip.model.docmodelreport;

import javax.xml.bind.annotation.XmlEnum;
import javax.xml.bind.annotation.XmlEnumValue;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for FlowProcessStepStepType.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * <p>
 * <pre>
 * &lt;simpleType name="FlowProcessStepStepType"&gt;
 *   &lt;restriction base="{http://www.w3.org/2001/XMLSchema}normalizedString"&gt;
 *     &lt;enumeration value="Mapping"/&gt;
 *     &lt;enumeration value="Rule"/&gt;
 *     &lt;enumeration value="Information Request"/&gt;
 *   &lt;/restriction&gt;
 * &lt;/simpleType&gt;
 * </pre>
 * 
 */
@XmlType(name = "FlowProcessStepStepType")
@XmlEnum
public enum FlowProcessStepStepType {

    @XmlEnumValue("Mapping")
    MAPPING("Mapping"),
    @XmlEnumValue("Rule")
    RULE("Rule"),
    @XmlEnumValue("Information Request")
    INFORMATION_REQUEST("Information Request");
    private final String value;

    FlowProcessStepStepType(String v) {
        value = v;
    }

    public String value() {
        return value;
    }

    public static FlowProcessStepStepType fromValue(String v) {
        for (FlowProcessStepStepType c: FlowProcessStepStepType.values()) {
            if (c.value.equals(v)) {
                return c;
            }
        }
        throw new IllegalArgumentException(v);
    }

}
