//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.11 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2016.10.25 at 11:10:15 AM CEST 
//


package com.qpark.eip.model.docmodelreport;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlSchemaType;
import javax.xml.bind.annotation.XmlType;
import javax.xml.bind.annotation.adapters.NormalizedStringAdapter;
import javax.xml.bind.annotation.adapters.XmlJavaTypeAdapter;


/**
 * <p>Java class for FlowProcessStepType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="FlowProcessStepType"&gt;
 *   &lt;complexContent&gt;
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *       &lt;sequence&gt;
 *         &lt;element name="flow" type="{http://www.w3.org/2001/XMLSchema}normalizedString"/&gt;
 *         &lt;element name="direction" type="{http://www.qpark-consulting.com/EIP/Utility/DocumentationModelReport}FlowProcessStepDirectionType"/&gt;
 *         &lt;element name="inputOutput" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
 *         &lt;element name="type" type="{http://www.qpark-consulting.com/EIP/Utility/DocumentationModelReport}FlowProcessStepStepType"/&gt;
 *         &lt;element name="processingStep" type="{http://www.w3.org/2001/XMLSchema}normalizedString"/&gt;
 *         &lt;element name="description" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&gt;
 *         &lt;element name="mappingInputTypes" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&gt;
 *       &lt;/sequence&gt;
 *     &lt;/restriction&gt;
 *   &lt;/complexContent&gt;
 * &lt;/complexType&gt;
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "FlowProcessStepType", propOrder = {
    "flow",
    "direction",
    "inputOutput",
    "type",
    "processingStep",
    "description",
    "mappingInputTypes"
})
public class FlowProcessStepType {

    @XmlElement(required = true)
    @XmlJavaTypeAdapter(NormalizedStringAdapter.class)
    @XmlSchemaType(name = "normalizedString")
    protected String flow;
    @XmlElement(required = true)
    @XmlSchemaType(name = "normalizedString")
    protected FlowProcessStepDirectionType direction;
    @XmlElement(required = true)
    protected String inputOutput;
    @XmlElement(required = true)
    @XmlSchemaType(name = "normalizedString")
    protected FlowProcessStepStepType type;
    @XmlElement(required = true)
    @XmlJavaTypeAdapter(NormalizedStringAdapter.class)
    @XmlSchemaType(name = "normalizedString")
    protected String processingStep;
    protected String description;
    protected String mappingInputTypes;

    /**
     * Gets the value of the flow property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getFlow() {
        return flow;
    }

    /**
     * Sets the value of the flow property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setFlow(String value) {
        this.flow = value;
    }

    /**
     * Gets the value of the direction property.
     * 
     * @return
     *     possible object is
     *     {@link FlowProcessStepDirectionType }
     *     
     */
    public FlowProcessStepDirectionType getDirection() {
        return direction;
    }

    /**
     * Sets the value of the direction property.
     * 
     * @param value
     *     allowed object is
     *     {@link FlowProcessStepDirectionType }
     *     
     */
    public void setDirection(FlowProcessStepDirectionType value) {
        this.direction = value;
    }

    /**
     * Gets the value of the inputOutput property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getInputOutput() {
        return inputOutput;
    }

    /**
     * Sets the value of the inputOutput property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setInputOutput(String value) {
        this.inputOutput = value;
    }

    /**
     * Gets the value of the type property.
     * 
     * @return
     *     possible object is
     *     {@link FlowProcessStepStepType }
     *     
     */
    public FlowProcessStepStepType getType() {
        return type;
    }

    /**
     * Sets the value of the type property.
     * 
     * @param value
     *     allowed object is
     *     {@link FlowProcessStepStepType }
     *     
     */
    public void setType(FlowProcessStepStepType value) {
        this.type = value;
    }

    /**
     * Gets the value of the processingStep property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getProcessingStep() {
        return processingStep;
    }

    /**
     * Sets the value of the processingStep property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setProcessingStep(String value) {
        this.processingStep = value;
    }

    /**
     * Gets the value of the description property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getDescription() {
        return description;
    }

    /**
     * Sets the value of the description property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setDescription(String value) {
        this.description = value;
    }

    /**
     * Gets the value of the mappingInputTypes property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getMappingInputTypes() {
        return mappingInputTypes;
    }

    /**
     * Sets the value of the mappingInputTypes property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setMappingInputTypes(String value) {
        this.mappingInputTypes = value;
    }

}
