//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.11 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2016.10.25 at 11:10:15 AM CEST 
//


package com.qpark.eip.model.docmodelreport;

import javax.xml.bind.annotation.XmlRegistry;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the com.qpark.eip.model.docmodelreport package. 
 * <p>An ObjectFactory allows you to programatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {


    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: com.qpark.eip.model.docmodelreport
     * 
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link ServiceOperationType }
     * 
     */
    public ServiceOperationType createServiceOperationType() {
        return new ServiceOperationType();
    }

    /**
     * Create an instance of {@link FlowProcessStepType }
     * 
     */
    public FlowProcessStepType createFlowProcessStepType() {
        return new FlowProcessStepType();
    }

    /**
     * Create an instance of {@link FlowMappingInterfaceFieldType }
     * 
     */
    public FlowMappingInterfaceFieldType createFlowMappingInterfaceFieldType() {
        return new FlowMappingInterfaceFieldType();
    }

    /**
     * Create an instance of {@link UsedComplexTypeType }
     * 
     */
    public UsedComplexTypeType createUsedComplexTypeType() {
        return new UsedComplexTypeType();
    }

}
