//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.11 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2016.01.18 at 07:53:38 AM CET 
//


package com.qpark.eip.core.spring.lockedoperation.model;

import javax.xml.bind.annotation.XmlEnum;
import javax.xml.bind.annotation.XmlEnumValue;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for OperationStateEnumType.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * <p>
 * <pre>
 * &lt;simpleType name="OperationStateEnumType"&gt;
 *   &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string"&gt;
 *     &lt;enumeration value="Started"/&gt;
 *     &lt;enumeration value="Running"/&gt;
 *     &lt;enumeration value="Idle"/&gt;
 *     &lt;enumeration value="NotProvided"/&gt;
 *   &lt;/restriction&gt;
 * &lt;/simpleType&gt;
 * </pre>
 * 
 */
@XmlType(name = "OperationStateEnumType")
@XmlEnum
public enum OperationStateEnumType {

    @XmlEnumValue("Idle")
    IDLE("Idle"),
    @XmlEnumValue("NotProvided")
    NOT_PROVIDED("NotProvided"),
    @XmlEnumValue("Running")
    RUNNING("Running"),
    @XmlEnumValue("Started")
    STARTED("Started");
    public static OperationStateEnumType fromValue(String v) {
        for (OperationStateEnumType c: OperationStateEnumType.values()) {
            if (c.value.equals(v)) {
                return c;
            }
        }
        throw new IllegalArgumentException(v);
    }

    private final String value;

    OperationStateEnumType(String v) {
        value = v;
    }

    public String value() {
        return value;
    }

}
