//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.11 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2016.01.18 at 07:53:38 AM CET 
//


package com.qpark.eip.core.spring.lockedoperation.model;

import javax.xml.bind.annotation.XmlEnum;
import javax.xml.bind.annotation.XmlEnumValue;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for OperationEventEnumType.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * <p>
 * <pre>
 * &lt;simpleType name="OperationEventEnumType"&gt;
 *   &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string"&gt;
 *     &lt;enumeration value="Start"/&gt;
 *     &lt;enumeration value="Stop"/&gt;
 *     &lt;enumeration value="Block"/&gt;
 *     &lt;enumeration value="Unblock"/&gt;
 *     &lt;enumeration value="CheckState"/&gt;
 *   &lt;/restriction&gt;
 * &lt;/simpleType&gt;
 * </pre>
 * 
 */
@XmlType(name = "OperationEventEnumType")
@XmlEnum
public enum OperationEventEnumType {

    @XmlEnumValue("Block")
    BLOCK("Block"),
    @XmlEnumValue("CheckState")
    CHECK_STATE("CheckState"),
    @XmlEnumValue("Start")
    START("Start"),
    @XmlEnumValue("Stop")
    STOP("Stop"),
    @XmlEnumValue("Unblock")
    UNBLOCK("Unblock");
    public static OperationEventEnumType fromValue(String v) {
        for (OperationEventEnumType c: OperationEventEnumType.values()) {
            if (c.value.equals(v)) {
                return c;
            }
        }
        throw new IllegalArgumentException(v);
    }

    private final String value;

    OperationEventEnumType(String v) {
        value = v;
    }

    public String value() {
        return value;
    }

}
