//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.11 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2016.01.18 at 07:53:38 AM CET 
//


package com.qpark.eip.core.spring.lockedoperation.model;

import java.io.Serializable;
import java.util.Date;
import javax.persistence.Basic;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.Inheritance;
import javax.persistence.InheritanceType;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;
import javax.persistence.Transient;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlSchemaType;
import javax.xml.bind.annotation.XmlTransient;
import javax.xml.bind.annotation.XmlType;
import javax.xml.bind.annotation.adapters.NormalizedStringAdapter;
import javax.xml.bind.annotation.adapters.XmlJavaTypeAdapter;
import javax.xml.datatype.XMLGregorianCalendar;
import org.jvnet.hyperjaxb3.xml.bind.annotation.adapters.XMLGregorianCalendarAsDateTime;
import org.jvnet.hyperjaxb3.xml.bind.annotation.adapters.XmlAdapterUtils;
import org.jvnet.jaxb2_commons.lang.Equals;
import org.jvnet.jaxb2_commons.lang.EqualsStrategy;
import org.jvnet.jaxb2_commons.lang.HashCode;
import org.jvnet.jaxb2_commons.lang.HashCodeStrategy;
import org.jvnet.jaxb2_commons.lang.JAXBEqualsStrategy;
import org.jvnet.jaxb2_commons.lang.JAXBHashCodeStrategy;
import org.jvnet.jaxb2_commons.locator.ObjectLocator;
import org.jvnet.jaxb2_commons.locator.util.LocatorUtils;


/**
 * Lock a specific process to be run just once during in a load balanced environment.
 * 
 * <p>Java class for OperationLockControllType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="OperationLockControllType"&gt;
 *   &lt;complexContent&gt;
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *       &lt;sequence&gt;
 *         &lt;element name="serverName" type="{http://www.w3.org/2001/XMLSchema}normalizedString"/&gt;
 *         &lt;element name="serverIpAddress" type="{http://www.w3.org/2001/XMLSchema}normalizedString"/&gt;
 *         &lt;element name="operationName" type="{http://www.w3.org/2001/XMLSchema}normalizedString"/&gt;
 *         &lt;element name="lockDate" type="{http://www.w3.org/2001/XMLSchema}dateTime"/&gt;
 *       &lt;/sequence&gt;
 *     &lt;/restriction&gt;
 *   &lt;/complexContent&gt;
 * &lt;/complexType&gt;
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "OperationLockControllType", propOrder = {
    "serverName",
    "serverIpAddress",
    "operationName",
    "lockDate"
})
@Entity(name = "OperationLockControllType")
@Table(name = "OPERATIONLOCKCONTROLLTYPE")
@Inheritance(strategy = InheritanceType.JOINED)
public class OperationLockControllType
    implements Serializable, Equals, HashCode
{

    @XmlTransient
    protected Long hjid;
    @XmlElement(required = true)
    @XmlSchemaType(name = "dateTime")
    protected XMLGregorianCalendar lockDate;
    @XmlElement(required = true)
    @XmlJavaTypeAdapter(NormalizedStringAdapter.class)
    @XmlSchemaType(name = "normalizedString")
    protected String operationName;
    @XmlElement(required = true)
    @XmlJavaTypeAdapter(NormalizedStringAdapter.class)
    @XmlSchemaType(name = "normalizedString")
    protected String serverIpAddress;
    @XmlElement(required = true)
    @XmlJavaTypeAdapter(NormalizedStringAdapter.class)
    @XmlSchemaType(name = "normalizedString")
    protected String serverName;

    public boolean equals(Object object) {
        final EqualsStrategy strategy = JAXBEqualsStrategy.INSTANCE;
        return equals(null, null, object, strategy);
    }

    public boolean equals(ObjectLocator thisLocator, ObjectLocator thatLocator, Object object, EqualsStrategy strategy) {
        if ((object == null)||(this.getClass()!= object.getClass())) {
            return false;
        }
        if (this == object) {
            return true;
        }
        final OperationLockControllType that = ((OperationLockControllType) object);
        {
            String lhsServerName;
            lhsServerName = this.getServerName();
            String rhsServerName;
            rhsServerName = that.getServerName();
            if (!strategy.equals(LocatorUtils.property(thisLocator, "serverName", lhsServerName), LocatorUtils.property(thatLocator, "serverName", rhsServerName), lhsServerName, rhsServerName)) {
                return false;
            }
        }
        {
            String lhsServerIpAddress;
            lhsServerIpAddress = this.getServerIpAddress();
            String rhsServerIpAddress;
            rhsServerIpAddress = that.getServerIpAddress();
            if (!strategy.equals(LocatorUtils.property(thisLocator, "serverIpAddress", lhsServerIpAddress), LocatorUtils.property(thatLocator, "serverIpAddress", rhsServerIpAddress), lhsServerIpAddress, rhsServerIpAddress)) {
                return false;
            }
        }
        {
            String lhsOperationName;
            lhsOperationName = this.getOperationName();
            String rhsOperationName;
            rhsOperationName = that.getOperationName();
            if (!strategy.equals(LocatorUtils.property(thisLocator, "operationName", lhsOperationName), LocatorUtils.property(thatLocator, "operationName", rhsOperationName), lhsOperationName, rhsOperationName)) {
                return false;
            }
        }
        {
            XMLGregorianCalendar lhsLockDate;
            lhsLockDate = this.getLockDate();
            XMLGregorianCalendar rhsLockDate;
            rhsLockDate = that.getLockDate();
            if (!strategy.equals(LocatorUtils.property(thisLocator, "lockDate", lhsLockDate), LocatorUtils.property(thatLocator, "lockDate", rhsLockDate), lhsLockDate, rhsLockDate)) {
                return false;
            }
        }
        return true;
    }

    /**
     * 
     * 
     * @return
     *     possible object is
     *     {@link Long }
     *     
     */
    @Id
    @Column(name = "HJID")
    @GeneratedValue(strategy = GenerationType.AUTO)
    public Long getHjid() {
        return hjid;
    }

    /**
     * Gets the value of the lockDate property.
     * 
     * @return
     *     possible object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    @Transient
    public XMLGregorianCalendar getLockDate() {
        return lockDate;
    }

    @Basic
    @Column(name = "LOCKDATEITEM")
    @Temporal(TemporalType.TIMESTAMP)
    public Date getLockDateItem() {
        return XmlAdapterUtils.unmarshall(XMLGregorianCalendarAsDateTime.class, this.getLockDate());
    }

    /**
     * Gets the value of the operationName property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    @Basic
    @Column(name = "OPERATIONNAME", length = 255)
    public String getOperationName() {
        return operationName;
    }

    /**
     * Gets the value of the serverIpAddress property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    @Basic
    @Column(name = "SERVERIPADDRESS", length = 255)
    public String getServerIpAddress() {
        return serverIpAddress;
    }

    /**
     * Gets the value of the serverName property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    @Basic
    @Column(name = "SERVERNAME", length = 255)
    public String getServerName() {
        return serverName;
    }

    public int hashCode() {
        final HashCodeStrategy strategy = JAXBHashCodeStrategy.INSTANCE;
        return this.hashCode(null, strategy);
    }

    public int hashCode(ObjectLocator locator, HashCodeStrategy strategy) {
        int currentHashCode = 1;
        {
            String theServerName;
            theServerName = this.getServerName();
            currentHashCode = strategy.hashCode(LocatorUtils.property(locator, "serverName", theServerName), currentHashCode, theServerName);
        }
        {
            String theServerIpAddress;
            theServerIpAddress = this.getServerIpAddress();
            currentHashCode = strategy.hashCode(LocatorUtils.property(locator, "serverIpAddress", theServerIpAddress), currentHashCode, theServerIpAddress);
        }
        {
            String theOperationName;
            theOperationName = this.getOperationName();
            currentHashCode = strategy.hashCode(LocatorUtils.property(locator, "operationName", theOperationName), currentHashCode, theOperationName);
        }
        {
            XMLGregorianCalendar theLockDate;
            theLockDate = this.getLockDate();
            currentHashCode = strategy.hashCode(LocatorUtils.property(locator, "lockDate", theLockDate), currentHashCode, theLockDate);
        }
        return currentHashCode;
    }

    @Transient
    public boolean isSetLockDate() {
        return (this.lockDate!= null);
    }

    @Transient
    public boolean isSetOperationName() {
        return (this.operationName!= null);
    }

    @Transient
    public boolean isSetServerIpAddress() {
        return (this.serverIpAddress!= null);
    }

    @Transient
    public boolean isSetServerName() {
        return (this.serverName!= null);
    }

    /**
     * 
     * 
     * @param value
     *     allowed object is
     *     {@link Long }
     *     
     */
    public void setHjid(Long value) {
        this.hjid = value;
    }

    /**
     * Sets the value of the lockDate property.
     * 
     * @param value
     *     allowed object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public void setLockDate(XMLGregorianCalendar value) {
        this.lockDate = value;
    }

    public void setLockDateItem(Date target) {
        setLockDate(XmlAdapterUtils.marshall(XMLGregorianCalendarAsDateTime.class, target));
    }

    /**
     * Sets the value of the operationName property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setOperationName(String value) {
        this.operationName = value;
    }

    /**
     * Sets the value of the serverIpAddress property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setServerIpAddress(String value) {
        this.serverIpAddress = value;
    }

    /**
     * Sets the value of the serverName property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setServerName(String value) {
        this.serverName = value;
    }

}
