//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.11 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2016.01.18 at 07:53:38 AM CET 
//


package com.qpark.eip.core.spring.lockedoperation.model;

import java.io.Serializable;
import javax.persistence.Basic;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.EnumType;
import javax.persistence.Enumerated;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.Inheritance;
import javax.persistence.InheritanceType;
import javax.persistence.Table;
import javax.persistence.Transient;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlSchemaType;
import javax.xml.bind.annotation.XmlTransient;
import javax.xml.bind.annotation.XmlType;
import javax.xml.bind.annotation.adapters.NormalizedStringAdapter;
import javax.xml.bind.annotation.adapters.XmlJavaTypeAdapter;
import org.jvnet.jaxb2_commons.lang.Equals;
import org.jvnet.jaxb2_commons.lang.EqualsStrategy;
import org.jvnet.jaxb2_commons.lang.HashCode;
import org.jvnet.jaxb2_commons.lang.HashCodeStrategy;
import org.jvnet.jaxb2_commons.lang.JAXBEqualsStrategy;
import org.jvnet.jaxb2_commons.lang.JAXBHashCodeStrategy;
import org.jvnet.jaxb2_commons.locator.ObjectLocator;
import org.jvnet.jaxb2_commons.locator.util.LocatorUtils;


/**
 * <p>Java class for OperationStateType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="OperationStateType"&gt;
 *   &lt;complexContent&gt;
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *       &lt;sequence&gt;
 *         &lt;element name="operationUUID" type="{http://www.ses.com/CommonTypes-1.0}UUIDType"/&gt;
 *         &lt;element name="state" type="{http://www.ses.com/Utility/AppControlling/AppControlling-1.0}OperationStateEnumType"/&gt;
 *       &lt;/sequence&gt;
 *     &lt;/restriction&gt;
 *   &lt;/complexContent&gt;
 * &lt;/complexType&gt;
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "OperationStateType", propOrder = {
    "operationUUID",
    "state"
})
@Entity(name = "OperationStateType")
@Table(name = "OPERATIONSTATETYPE")
@Inheritance(strategy = InheritanceType.JOINED)
public class OperationStateType
    implements Serializable, Equals, HashCode
{

    @XmlTransient
    protected Long hjid;
    @XmlElement(required = true)
    @XmlJavaTypeAdapter(NormalizedStringAdapter.class)
    @XmlSchemaType(name = "normalizedString")
    protected String operationUUID;
    @XmlElement(required = true)
    @XmlSchemaType(name = "string")
    protected OperationStateEnumType state;

    public boolean equals(Object object) {
        final EqualsStrategy strategy = JAXBEqualsStrategy.INSTANCE;
        return equals(null, null, object, strategy);
    }

    public boolean equals(ObjectLocator thisLocator, ObjectLocator thatLocator, Object object, EqualsStrategy strategy) {
        if ((object == null)||(this.getClass()!= object.getClass())) {
            return false;
        }
        if (this == object) {
            return true;
        }
        final OperationStateType that = ((OperationStateType) object);
        {
            String lhsOperationUUID;
            lhsOperationUUID = this.getOperationUUID();
            String rhsOperationUUID;
            rhsOperationUUID = that.getOperationUUID();
            if (!strategy.equals(LocatorUtils.property(thisLocator, "operationUUID", lhsOperationUUID), LocatorUtils.property(thatLocator, "operationUUID", rhsOperationUUID), lhsOperationUUID, rhsOperationUUID)) {
                return false;
            }
        }
        {
            OperationStateEnumType lhsState;
            lhsState = this.getState();
            OperationStateEnumType rhsState;
            rhsState = that.getState();
            if (!strategy.equals(LocatorUtils.property(thisLocator, "state", lhsState), LocatorUtils.property(thatLocator, "state", rhsState), lhsState, rhsState)) {
                return false;
            }
        }
        return true;
    }

    /**
     * 
     * 
     * @return
     *     possible object is
     *     {@link Long }
     *     
     */
    @Id
    @Column(name = "HJID")
    @GeneratedValue(strategy = GenerationType.AUTO)
    public Long getHjid() {
        return hjid;
    }

    /**
     * Gets the value of the operationUUID property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    @Basic
    @Column(name = "OPERATIONUUID", length = 36)
    public String getOperationUUID() {
        return operationUUID;
    }

    /**
     * Gets the value of the state property.
     * 
     * @return
     *     possible object is
     *     {@link OperationStateEnumType }
     *     
     */
    @Basic
    @Column(name = "STATE_", length = 255)
    @Enumerated(EnumType.STRING)
    public OperationStateEnumType getState() {
        return state;
    }

    public int hashCode() {
        final HashCodeStrategy strategy = JAXBHashCodeStrategy.INSTANCE;
        return this.hashCode(null, strategy);
    }

    public int hashCode(ObjectLocator locator, HashCodeStrategy strategy) {
        int currentHashCode = 1;
        {
            String theOperationUUID;
            theOperationUUID = this.getOperationUUID();
            currentHashCode = strategy.hashCode(LocatorUtils.property(locator, "operationUUID", theOperationUUID), currentHashCode, theOperationUUID);
        }
        {
            OperationStateEnumType theState;
            theState = this.getState();
            currentHashCode = strategy.hashCode(LocatorUtils.property(locator, "state", theState), currentHashCode, theState);
        }
        return currentHashCode;
    }

    @Transient
    public boolean isSetOperationUUID() {
        return (this.operationUUID!= null);
    }

    @Transient
    public boolean isSetState() {
        return (this.state!= null);
    }

    /**
     * 
     * 
     * @param value
     *     allowed object is
     *     {@link Long }
     *     
     */
    public void setHjid(Long value) {
        this.hjid = value;
    }

    /**
     * Sets the value of the operationUUID property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setOperationUUID(String value) {
        this.operationUUID = value;
    }

    /**
     * Sets the value of the state property.
     * 
     * @param value
     *     allowed object is
     *     {@link OperationStateEnumType }
     *     
     */
    public void setState(OperationStateEnumType value) {
        this.state = value;
    }

}
