-----------------------------------------------------------------------------
-- Create script of persistence unit com.qpark.eip.core.persistence.ddl.
-- Generated at 20160121-101042.621.
-----------------------------------------------------------------------------
-- Verify sequence handling at the end of the script

CREATE TABLE APPLICATIONUSERLOGTYPE (HJID NUMBER(19) NOT NULL, DTYPE VARCHAR2(31) NULL, CLIENTSESSIONID VARCHAR2(255) NULL, CONTEXT VARCHAR2(255) NULL, DURATIONMILLIS NUMBER(20) NULL, DURATIONSTRING VARCHAR2(255) NULL, HOSTNAME VARCHAR2(255) NULL, OPERATIONNAME VARCHAR2(255) NULL, RETURNEDENTITIES NUMBER(10) NULL, RETURNEDFAILURES NUMBER(10) NULL, SERVICENAME VARCHAR2(255) NULL, STARTITEM TIMESTAMP NULL, STOPITEM TIMESTAMP NULL, USERNAME VARCHAR2(255) NULL, VERSION_ VARCHAR2(255) NULL, PRIMARY KEY (HJID));
CREATE TABLE AUTHENTICATIONTYPE (HJID NUMBER(19) NOT NULL, DTYPE VARCHAR2(31) NULL, CONTEXT VARCHAR2(255) NULL, ENABLED NUMBER(1) default 0 NULL, PASSWORD_ VARCHAR2(255) NULL, USERNAME VARCHAR2(255) NULL, AUTHENTICATION_CONTEXTTYPE_H_0 NUMBER(19) NULL, PRIMARY KEY (HJID));
CREATE INDEX THNTHNTCTNTYPTHNTCTNCNTXTTYPH0 ON AUTHENTICATIONTYPE (AUTHENTICATION_CONTEXTTYPE_H_0);
CREATE TABLE CONTEXTLISTTYPE (HJID NUMBER(19) NOT NULL, DTYPE VARCHAR2(31) NULL, PRIMARY KEY (HJID));
CREATE TABLE CONTEXTTYPE (HJID NUMBER(19) NOT NULL, DTYPE VARCHAR2(31) NULL, CONTEXT VARCHAR2(255) NULL, CONTEXT_CONTEXTLISTTYPE_HJID NUMBER(19) NULL, PRIMARY KEY (HJID));
CREATE INDEX CNTCNTXTTYPCNTXTCNTXTLSTTYPHJD ON CONTEXTTYPE (CONTEXT_CONTEXTLISTTYPE_HJID);
CREATE TABLE FLOWLOGMESSAGETYPE (HJID NUMBER(19) NOT NULL, DTYPE VARCHAR2(31) NULL, CLASSIFICATION VARCHAR2(255) NULL, DATADESCRIPTION VARCHAR2(255) NULL, FLOWIDENTIFIER VARCHAR2(255) NULL, FLOWNAME VARCHAR2(255) NULL, FLOWSESSION VARCHAR2(255) NULL, FLOWSTEP VARCHAR2(255) NULL, LOGMESSAGETYPE VARCHAR2(255) NULL, LOGTIMEITEM TIMESTAMP NULL, SEVERITY VARCHAR2(255) NULL, SUBCLASSIFICATION VARCHAR2(255) NULL, PRIMARY KEY (HJID));
CREATE TABLE GRANTEDAUTHORITYTYPE (HJID NUMBER(19) NOT NULL, DTYPE VARCHAR2(31) NULL, MAXREQUESTS NUMBER(10) NULL, ROLENAME VARCHAR2(255) NULL, GRANTEDAUTHORITY_AUTHENTICAT_0 NUMBER(19) NULL, PRIMARY KEY (HJID));
CREATE INDEX GRNTDTHRTYTYPGRNTDTHRTYTHNTCT0 ON GRANTEDAUTHORITYTYPE (GRANTEDAUTHORITY_AUTHENTICAT_0);
CREATE TABLE SYSTEMUSERLOGTYPE (HJID NUMBER(19) NOT NULL, DTYPE VARCHAR2(31) NULL, CONTEXT VARCHAR2(255) NULL, LOGDATEITEM DATE NULL, OPERATIONNAME VARCHAR2(255) NULL, REQUESTSDENIED NUMBER(10) NULL, REQUESTSGRANTED NUMBER(10) NULL, RESPONSEFAULTS NUMBER(10) NULL, SERVICENAME VARCHAR2(255) NULL, USERNAME VARCHAR2(255) NULL, VERSION_ VARCHAR2(255) NULL, PRIMARY KEY (HJID));
CREATE TABLE OPERATIONEVENTTYPE (HJID NUMBER(19) NOT NULL, DTYPE VARCHAR2(31) NULL, EVENT VARCHAR2(255) NULL, OPERATIONTIMEITEM TIMESTAMP NULL, OPERATIONUUID VARCHAR2(36) NULL, PRIMARY KEY (HJID));
CREATE TABLE OPERATIONLOCKCONTROLLTYPE (HJID NUMBER(19) NOT NULL, DTYPE VARCHAR2(31) NULL, LOCKDATEITEM TIMESTAMP NULL, OPERATIONNAME VARCHAR2(255) NULL, SERVERIPADDRESS VARCHAR2(255) NULL, SERVERNAME VARCHAR2(255) NULL, PRIMARY KEY (HJID));
CREATE TABLE OPERATIONSTATETYPE (HJID NUMBER(19) NOT NULL, DTYPE VARCHAR2(31) NULL, OPERATIONUUID VARCHAR2(36) NULL, STATE_ VARCHAR2(255) NULL, PRIMARY KEY (HJID));
ALTER TABLE AUTHENTICATIONTYPE ADD CONSTRAINT THNTCTNTYPETHNTCTNCNTEXTTYPEH0 FOREIGN KEY (AUTHENTICATION_CONTEXTTYPE_H_0) REFERENCES CONTEXTTYPE (HJID);
ALTER TABLE CONTEXTTYPE ADD CONSTRAINT CNTXTTYPCNTXTCNTXTLISTTYPEHJID FOREIGN KEY (CONTEXT_CONTEXTLISTTYPE_HJID) REFERENCES CONTEXTLISTTYPE (HJID);
ALTER TABLE GRANTEDAUTHORITYTYPE ADD CONSTRAINT GRNTDTHRTYTYPGRNTDTHRTYTHNTCT0 FOREIGN KEY (GRANTEDAUTHORITY_AUTHENTICAT_0) REFERENCES AUTHENTICATIONTYPE (HJID);

-----------------------------------------------------------------------------
-- Hibernate sequence
-----------------------------------------------------------------------------
-- CREATE SEQUENCE hibernate_sequence;

-----------------------------------------------------------------------------
-- EclipseLink sequence
-----------------------------------------------------------------------------
-- CREATE TABLE SEQUENCE (SEQ_NAME VARCHAR2(50) NOT NULL, SEQ_COUNT NUMBER(38) NULL, PRIMARY KEY (SEQ_NAME));
-- INSERT INTO SEQUENCE(SEQ_NAME, SEQ_COUNT) values ('SEQ_GEN', 0);
