-----------------------------------------------------------------------------
-- Drop script of persistence unit com.qpark.eip.core.persistence.ddl.
-- Generated at 20160121-101042.621.
-----------------------------------------------------------------------------
-- Verify sequence handling at the end of the script

ALTER TABLE AUTHENTICATIONTYPE DROP CONSTRAINT THNTCTNTYPETHNTCTNCNTEXTTYPEH0;
ALTER TABLE CONTEXTTYPE DROP CONSTRAINT CNTXTTYPCNTXTCNTXTLISTTYPEHJID;
ALTER TABLE GRANTEDAUTHORITYTYPE DROP CONSTRAINT GRNTDTHRTYTYPGRNTDTHRTYTHNTCT0;
DROP TABLE APPLICATIONUSERLOGTYPE CASCADE CONSTRAINTS;
DROP INDEX THNTHNTCTNTYPTHNTCTNCNTXTTYPH0;
DROP TABLE AUTHENTICATIONTYPE CASCADE CONSTRAINTS;
DROP TABLE CONTEXTLISTTYPE CASCADE CONSTRAINTS;
DROP INDEX CNTCNTXTTYPCNTXTCNTXTLSTTYPHJD;
DROP TABLE CONTEXTTYPE CASCADE CONSTRAINTS;
DROP TABLE FLOWLOGMESSAGETYPE CASCADE CONSTRAINTS;
DROP INDEX GRNTDTHRTYTYPGRNTDTHRTYTHNTCT0;
DROP TABLE GRANTEDAUTHORITYTYPE CASCADE CONSTRAINTS;
DROP TABLE SYSTEMUSERLOGTYPE CASCADE CONSTRAINTS;
DROP TABLE OPERATIONEVENTTYPE CASCADE CONSTRAINTS;
DROP TABLE OPERATIONLOCKCONTROLLTYPE CASCADE CONSTRAINTS;
DROP TABLE OPERATIONSTATETYPE CASCADE CONSTRAINTS;

-----------------------------------------------------------------------------
-- Hibernate sequence
-----------------------------------------------------------------------------
-- DROP SEQUENCE hibernate_sequence;

-----------------------------------------------------------------------------
-- EclipseLink sequence
-----------------------------------------------------------------------------
-- -- DELETE FROM SEQUENCE WHERE SEQ_NAME = 'SEQ_GEN';
