//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.11 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2018.09.19 at 04:46:23 PM CEST 
//

@javax.xml.bind.annotation.XmlSchema(namespace = "http://www.qpark-consulting.com/EIP/Utility/ReportingModel")
package com.qpark.eip.model.reporting;
