//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.11 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2018.09.19 at 04:46:23 PM CEST 
//


package com.qpark.eip.model.reporting;

import java.io.Serializable;
import java.util.ArrayList;
import java.util.List;
import javax.persistence.Basic;
import javax.persistence.CascadeType;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.Inheritance;
import javax.persistence.InheritanceType;
import javax.persistence.JoinColumn;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.Transient;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlTransient;
import javax.xml.bind.annotation.XmlType;
import org.jvnet.jaxb2_commons.lang.Equals;
import org.jvnet.jaxb2_commons.lang.EqualsStrategy;
import org.jvnet.jaxb2_commons.lang.HashCode;
import org.jvnet.jaxb2_commons.lang.HashCodeStrategy;
import org.jvnet.jaxb2_commons.lang.JAXBEqualsStrategy;
import org.jvnet.jaxb2_commons.lang.JAXBHashCodeStrategy;
import org.jvnet.jaxb2_commons.locator.ObjectLocator;
import org.jvnet.jaxb2_commons.locator.util.LocatorUtils;


/**
 * <p>Java class for ReportHeaderDataType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="ReportHeaderDataType"&gt;
 *   &lt;complexContent&gt;
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *       &lt;sequence&gt;
 *         &lt;element name="rowNumber" type="{http://www.w3.org/2001/XMLSchema}int"/&gt;
 *         &lt;element name="reportMetaData" type="{http://www.qpark-consulting.com/EIP/Utility/ReportingModel}ReportMetaDataType" maxOccurs="unbounded"/&gt;
 *         &lt;element name="finalRow" type="{http://www.w3.org/2001/XMLSchema}boolean"/&gt;
 *       &lt;/sequence&gt;
 *     &lt;/restriction&gt;
 *   &lt;/complexContent&gt;
 * &lt;/complexType&gt;
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "ReportHeaderDataType", propOrder = {
    "rowNumber",
    "reportMetaData",
    "finalRow"
})
@Entity(name = "ReportHeaderDataType")
@Table(name = "REPORTHEADERDATATYPE")
@Inheritance(strategy = InheritanceType.JOINED)
public class ReportHeaderDataType
    implements Serializable, Equals, HashCode
{

    protected int rowNumber;
    @XmlElement(required = true)
    protected List<ReportMetaDataType> reportMetaData;
    protected boolean finalRow;
    @XmlTransient
    protected Long hjid;

    /**
     * Gets the value of the rowNumber property.
     * 
     */
    @Basic
    @Column(name = "ROWNUMBER", precision = 10, scale = 0)
    public int getRowNumber() {
        return rowNumber;
    }

    /**
     * Sets the value of the rowNumber property.
     * 
     */
    public void setRowNumber(int value) {
        this.rowNumber = value;
    }

    @Transient
    public boolean isSetRowNumber() {
        return true;
    }

    /**
     * Gets the value of the reportMetaData property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the reportMetaData property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getReportMetaData().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link ReportMetaDataType }
     * 
     * 
     */
    @OneToMany(targetEntity = ReportMetaDataType.class, cascade = {
        CascadeType.ALL
    })
    @JoinColumn(name = "REPORTMETADATA_REPORTHEADERD_0")
    public List<ReportMetaDataType> getReportMetaData() {
        if (reportMetaData == null) {
            reportMetaData = new ArrayList<ReportMetaDataType>();
        }
        return this.reportMetaData;
    }

    /**
     * 
     * 
     */
    public void setReportMetaData(List<ReportMetaDataType> reportMetaData) {
        this.reportMetaData = reportMetaData;
    }

    @Transient
    public boolean isSetReportMetaData() {
        return ((this.reportMetaData!= null)&&(!this.reportMetaData.isEmpty()));
    }

    public void unsetReportMetaData() {
        this.reportMetaData = null;
    }

    /**
     * Gets the value of the finalRow property.
     * 
     */
    @Basic
    @Column(name = "FINALROW")
    public boolean isFinalRow() {
        return finalRow;
    }

    /**
     * Sets the value of the finalRow property.
     * 
     */
    public void setFinalRow(boolean value) {
        this.finalRow = value;
    }

    @Transient
    public boolean isSetFinalRow() {
        return true;
    }

    /**
     * 
     * 
     * @return
     *     possible object is
     *     {@link Long }
     *     
     */
    @Id
    @Column(name = "HJID")
    @GeneratedValue(strategy = GenerationType.AUTO)
    public Long getHjid() {
        return hjid;
    }

    /**
     * 
     * 
     * @param value
     *     allowed object is
     *     {@link Long }
     *     
     */
    public void setHjid(Long value) {
        this.hjid = value;
    }

    public boolean equals(ObjectLocator thisLocator, ObjectLocator thatLocator, Object object, EqualsStrategy strategy) {
        if ((object == null)||(this.getClass()!= object.getClass())) {
            return false;
        }
        if (this == object) {
            return true;
        }
        final ReportHeaderDataType that = ((ReportHeaderDataType) object);
        {
            int lhsRowNumber;
            lhsRowNumber = this.getRowNumber();
            int rhsRowNumber;
            rhsRowNumber = that.getRowNumber();
            if (!strategy.equals(LocatorUtils.property(thisLocator, "rowNumber", lhsRowNumber), LocatorUtils.property(thatLocator, "rowNumber", rhsRowNumber), lhsRowNumber, rhsRowNumber)) {
                return false;
            }
        }
        {
            List<ReportMetaDataType> lhsReportMetaData;
            lhsReportMetaData = (this.isSetReportMetaData()?this.getReportMetaData():null);
            List<ReportMetaDataType> rhsReportMetaData;
            rhsReportMetaData = (that.isSetReportMetaData()?that.getReportMetaData():null);
            if (!strategy.equals(LocatorUtils.property(thisLocator, "reportMetaData", lhsReportMetaData), LocatorUtils.property(thatLocator, "reportMetaData", rhsReportMetaData), lhsReportMetaData, rhsReportMetaData)) {
                return false;
            }
        }
        {
            boolean lhsFinalRow;
            lhsFinalRow = this.isFinalRow();
            boolean rhsFinalRow;
            rhsFinalRow = that.isFinalRow();
            if (!strategy.equals(LocatorUtils.property(thisLocator, "finalRow", lhsFinalRow), LocatorUtils.property(thatLocator, "finalRow", rhsFinalRow), lhsFinalRow, rhsFinalRow)) {
                return false;
            }
        }
        return true;
    }

    public boolean equals(Object object) {
        final EqualsStrategy strategy = JAXBEqualsStrategy.INSTANCE;
        return equals(null, null, object, strategy);
    }

    public int hashCode(ObjectLocator locator, HashCodeStrategy strategy) {
        int currentHashCode = 1;
        {
            int theRowNumber;
            theRowNumber = this.getRowNumber();
            currentHashCode = strategy.hashCode(LocatorUtils.property(locator, "rowNumber", theRowNumber), currentHashCode, theRowNumber);
        }
        {
            List<ReportMetaDataType> theReportMetaData;
            theReportMetaData = (this.isSetReportMetaData()?this.getReportMetaData():null);
            currentHashCode = strategy.hashCode(LocatorUtils.property(locator, "reportMetaData", theReportMetaData), currentHashCode, theReportMetaData);
        }
        {
            boolean theFinalRow;
            theFinalRow = this.isFinalRow();
            currentHashCode = strategy.hashCode(LocatorUtils.property(locator, "finalRow", theFinalRow), currentHashCode, theFinalRow);
        }
        return currentHashCode;
    }

    public int hashCode() {
        final HashCodeStrategy strategy = JAXBHashCodeStrategy.INSTANCE;
        return this.hashCode(null, strategy);
    }

}
