//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.11 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2018.09.19 at 04:46:23 PM CEST 
//


package com.qpark.eip.model.reporting;

import java.io.Serializable;
import javax.persistence.Basic;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.Inheritance;
import javax.persistence.InheritanceType;
import javax.persistence.Table;
import javax.persistence.Transient;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlTransient;
import javax.xml.bind.annotation.XmlType;
import org.jvnet.jaxb2_commons.lang.Equals;
import org.jvnet.jaxb2_commons.lang.EqualsStrategy;
import org.jvnet.jaxb2_commons.lang.HashCode;
import org.jvnet.jaxb2_commons.lang.HashCodeStrategy;
import org.jvnet.jaxb2_commons.lang.JAXBEqualsStrategy;
import org.jvnet.jaxb2_commons.lang.JAXBHashCodeStrategy;
import org.jvnet.jaxb2_commons.locator.ObjectLocator;
import org.jvnet.jaxb2_commons.locator.util.LocatorUtils;


/**
 * <p>Java class for ReportInfoType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="ReportInfoType"&gt;
 *   &lt;complexContent&gt;
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *       &lt;sequence&gt;
 *         &lt;element name="numberOfHeaderRows" type="{http://www.w3.org/2001/XMLSchema}int"/&gt;
 *         &lt;element name="numberOfColumns" type="{http://www.w3.org/2001/XMLSchema}int"/&gt;
 *         &lt;element name="numberOfRows" type="{http://www.w3.org/2001/XMLSchema}int"/&gt;
 *         &lt;element name="delimiter" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
 *       &lt;/sequence&gt;
 *     &lt;/restriction&gt;
 *   &lt;/complexContent&gt;
 * &lt;/complexType&gt;
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "ReportInfoType", propOrder = {
    "numberOfHeaderRows",
    "numberOfColumns",
    "numberOfRows",
    "delimiter"
})
@Entity(name = "ReportInfoType")
@Table(name = "REPORTINFOTYPE")
@Inheritance(strategy = InheritanceType.JOINED)
public class ReportInfoType
    implements Serializable, Equals, HashCode
{

    protected int numberOfHeaderRows;
    protected int numberOfColumns;
    protected int numberOfRows;
    @XmlElement(required = true)
    protected String delimiter;
    @XmlTransient
    protected Long hjid;

    /**
     * Gets the value of the numberOfHeaderRows property.
     * 
     */
    @Basic
    @Column(name = "NUMBEROFHEADERROWS", precision = 10, scale = 0)
    public int getNumberOfHeaderRows() {
        return numberOfHeaderRows;
    }

    /**
     * Sets the value of the numberOfHeaderRows property.
     * 
     */
    public void setNumberOfHeaderRows(int value) {
        this.numberOfHeaderRows = value;
    }

    @Transient
    public boolean isSetNumberOfHeaderRows() {
        return true;
    }

    /**
     * Gets the value of the numberOfColumns property.
     * 
     */
    @Basic
    @Column(name = "NUMBEROFCOLUMNS", precision = 10, scale = 0)
    public int getNumberOfColumns() {
        return numberOfColumns;
    }

    /**
     * Sets the value of the numberOfColumns property.
     * 
     */
    public void setNumberOfColumns(int value) {
        this.numberOfColumns = value;
    }

    @Transient
    public boolean isSetNumberOfColumns() {
        return true;
    }

    /**
     * Gets the value of the numberOfRows property.
     * 
     */
    @Basic
    @Column(name = "NUMBEROFROWS", precision = 10, scale = 0)
    public int getNumberOfRows() {
        return numberOfRows;
    }

    /**
     * Sets the value of the numberOfRows property.
     * 
     */
    public void setNumberOfRows(int value) {
        this.numberOfRows = value;
    }

    @Transient
    public boolean isSetNumberOfRows() {
        return true;
    }

    /**
     * Gets the value of the delimiter property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    @Basic
    @Column(name = "DELIMITER_", length = 255)
    public String getDelimiter() {
        return delimiter;
    }

    /**
     * Sets the value of the delimiter property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setDelimiter(String value) {
        this.delimiter = value;
    }

    @Transient
    public boolean isSetDelimiter() {
        return (this.delimiter!= null);
    }

    /**
     * 
     * 
     * @return
     *     possible object is
     *     {@link Long }
     *     
     */
    @Id
    @Column(name = "HJID")
    @GeneratedValue(strategy = GenerationType.AUTO)
    public Long getHjid() {
        return hjid;
    }

    /**
     * 
     * 
     * @param value
     *     allowed object is
     *     {@link Long }
     *     
     */
    public void setHjid(Long value) {
        this.hjid = value;
    }

    public boolean equals(ObjectLocator thisLocator, ObjectLocator thatLocator, Object object, EqualsStrategy strategy) {
        if ((object == null)||(this.getClass()!= object.getClass())) {
            return false;
        }
        if (this == object) {
            return true;
        }
        final ReportInfoType that = ((ReportInfoType) object);
        {
            int lhsNumberOfHeaderRows;
            lhsNumberOfHeaderRows = this.getNumberOfHeaderRows();
            int rhsNumberOfHeaderRows;
            rhsNumberOfHeaderRows = that.getNumberOfHeaderRows();
            if (!strategy.equals(LocatorUtils.property(thisLocator, "numberOfHeaderRows", lhsNumberOfHeaderRows), LocatorUtils.property(thatLocator, "numberOfHeaderRows", rhsNumberOfHeaderRows), lhsNumberOfHeaderRows, rhsNumberOfHeaderRows)) {
                return false;
            }
        }
        {
            int lhsNumberOfColumns;
            lhsNumberOfColumns = this.getNumberOfColumns();
            int rhsNumberOfColumns;
            rhsNumberOfColumns = that.getNumberOfColumns();
            if (!strategy.equals(LocatorUtils.property(thisLocator, "numberOfColumns", lhsNumberOfColumns), LocatorUtils.property(thatLocator, "numberOfColumns", rhsNumberOfColumns), lhsNumberOfColumns, rhsNumberOfColumns)) {
                return false;
            }
        }
        {
            int lhsNumberOfRows;
            lhsNumberOfRows = this.getNumberOfRows();
            int rhsNumberOfRows;
            rhsNumberOfRows = that.getNumberOfRows();
            if (!strategy.equals(LocatorUtils.property(thisLocator, "numberOfRows", lhsNumberOfRows), LocatorUtils.property(thatLocator, "numberOfRows", rhsNumberOfRows), lhsNumberOfRows, rhsNumberOfRows)) {
                return false;
            }
        }
        {
            String lhsDelimiter;
            lhsDelimiter = this.getDelimiter();
            String rhsDelimiter;
            rhsDelimiter = that.getDelimiter();
            if (!strategy.equals(LocatorUtils.property(thisLocator, "delimiter", lhsDelimiter), LocatorUtils.property(thatLocator, "delimiter", rhsDelimiter), lhsDelimiter, rhsDelimiter)) {
                return false;
            }
        }
        return true;
    }

    public boolean equals(Object object) {
        final EqualsStrategy strategy = JAXBEqualsStrategy.INSTANCE;
        return equals(null, null, object, strategy);
    }

    public int hashCode(ObjectLocator locator, HashCodeStrategy strategy) {
        int currentHashCode = 1;
        {
            int theNumberOfHeaderRows;
            theNumberOfHeaderRows = this.getNumberOfHeaderRows();
            currentHashCode = strategy.hashCode(LocatorUtils.property(locator, "numberOfHeaderRows", theNumberOfHeaderRows), currentHashCode, theNumberOfHeaderRows);
        }
        {
            int theNumberOfColumns;
            theNumberOfColumns = this.getNumberOfColumns();
            currentHashCode = strategy.hashCode(LocatorUtils.property(locator, "numberOfColumns", theNumberOfColumns), currentHashCode, theNumberOfColumns);
        }
        {
            int theNumberOfRows;
            theNumberOfRows = this.getNumberOfRows();
            currentHashCode = strategy.hashCode(LocatorUtils.property(locator, "numberOfRows", theNumberOfRows), currentHashCode, theNumberOfRows);
        }
        {
            String theDelimiter;
            theDelimiter = this.getDelimiter();
            currentHashCode = strategy.hashCode(LocatorUtils.property(locator, "delimiter", theDelimiter), currentHashCode, theDelimiter);
        }
        return currentHashCode;
    }

    public int hashCode() {
        final HashCodeStrategy strategy = JAXBHashCodeStrategy.INSTANCE;
        return this.hashCode(null, strategy);
    }

}
