# Copyright (c) 2013-2020 QPark Consulting  S.a r.l.
#
# This program and the accompanying materials are made available under the
# terms of the Eclipse Public License v1.0.
# The Eclipse Public License is available at
# http://www.eclipse.org/legal/epl-v10.html.

FROM tomcat:9-jdk11-openjdk-slim
# FROM tomcat:10-jdk11-openjdk-slim
# tomcat 10 reports:
# SEVERE [main] org.apache.catalina.core.StandardContext.filterStart Exception starting filter [xxxFilter] java.lang.ClassCastException: class xxxFilter cannot be cast to class jakarta.servlet.Filter
# tomcat 10 removed the dependency on Java EE 8 and replaced it with Jakarta EE 9. There is a tool available at 
# https://github.com/apache/tomcat-jakartaee-migration
# to migrate a tomcat 9 valid war file into a tomcat 10 valid war file.


ADD tomcat/lib-platform-servicebus-2.0.0 /usr/local/tomcat/lib-platform-servicebus-2.0.0/
ADD tomcat/lib/* /usr/local/tomcat/lib/
ADD tomcat/conf/* /usr/local/tomcat/conf/
ADD tomcat/webapps/platform-webapp-library-xxx-application.version-xxx.war /usr/local/tomcat/webapps/iss-library.war

RUN sed -i 's/shared.loader=/shared.loader=\/usr\/local\/tomcat\/lib-platform-servicebus-2.0.0\/*.jar/g' /usr/local/tomcat/conf/catalina.properties; 
RUN sed -i 's/<\/Context>/<ResourceLink name="jdbc\/PlatformDB" type="javax.sql.DataSource" global="jdbc\/PlatformDB" \/><\/Context>/g' /usr/local/tomcat/conf/context.xml; 
RUN sed -i 's/<\/GlobalNamingResources>/<Resource name="jdbc\/PlatformDB" auth="Container" username="${eip.sample.database.userName}" password="${eip.sample.database.password}" url="${eip.sample.database.jdbc}" driverClassName="org.hsqldb.jdbc.JDBCDriver" factory="org.apache.tomcat.jdbc.pool.DataSourceFactory" type="javax.sql.DataSource" defaultTransactionIsolation="READ_COMMITTED" maxActive="20" maxIdle="20" minIdle="3" initialSize="2" \/><\/GlobalNamingResources>/g' /usr/local/tomcat/conf/server.xml; 
RUN sed -i 's/redirectPort="8443"\ \/>/redirectPort="8443" address="0.0.0.0" URIEncoding="UTF-8" ><UpgradeProtocol className="org.apache.coyote.http2.Http2Protocol" \/><\/Connector>/g' /usr/local/tomcat/conf/server.xml; 
#RUN sed -i "s/1catalina.org.apache.juli.AsyncFileHandler.level\ =\ FINE/1catalina.org.apache.juli.AsyncFileHandler.level=WARNING/g" /usr/local/tomcat/conf/logging.properties; 
#RUN echo "org.apache.catalina.startup.Catalina.level = INFO\norg.apache.catalina.startup.Catalina.handlers = java.util.logging.ConsoleHandler\njava.util.logging.SimpleFormatter.format=%1$tY%1$tm%1$td-%1$tH%1$tM%1$tS.%1$tL %2$s%n%4$s: %5$s%6$s%n" >> /usr/local/tomcat/conf/logging.properties;
RUN chmod 600 /usr/local/tomcat/conf/jmxremote.password;

EXPOSE 8080 8010 1099

ENV eip_jasypt_encryptor_password=qpark-eip

ENV CATALINA_OPTS="${CATALINA_OPTS} -Duser.timezone=UTC \
    -Duser.language=en \
    -Duser.region=GB \
    -Dcom.sun.management.jmxremote.port=1099 \
    -Dcom.sun.management.jmxremote.rmi.port=1099 \ 
    -Dcom.sun.management.jmxremote.ssl=false \
    -Dcom.sun.management.jmxremote.authenticate=false \
    -Dcom.sun.management.jmxremote.authenticate=true \
    -Dcom.sun.management.jmxremote.password.file=/usr/local/tomcat/conf/jmxremote.password \
    -Dcom.sun.management.jmxremote.access.file=/usr/local/tomcat/conf/jmxremote.access \
    -Deip.sample.database.jdbc=\${EIP_SAMPLE_DATABASE_JDBC_URL} \
    -Deip.sample.database.userName=\${EIP_SAMPLE_DATABASE_USERNAME} \
    -Deip.sample.database.password=\${EIP_SAMPLE_DATABASE_PASSWORD} \
    -Xmx512M \
    -Xms512M \
    -Xss256K \
    -XX:NewSize=128M \
    -XX:MaxNewSize=128M \
    -Xrunjdwp:transport=dt_socket,address=8010,server=y,suspend=n \
    -verbose:gc \
    -Xloggc:/usr/local/tomcat/logs/gc-eip-platform-$(date +%Y%m%d-%H%M%S).log"
