# Copyright (c) 2013-2020 QPark Consulting  S.a r.l.
#
# This program and the accompanying materials are made available under the
# terms of the Eclipse Public License v1.0.
# The Eclipse Public License is available at
# http://www.eclipse.org/legal/epl-v10.html.
version: "2.3"
services:
  iss-platform-sample:
    environment:
      eip_jasypt_encryptor_password: qpark-eip
      EIP_SAMPLE_DATABASE_JDBC_URL: jdbc:hsqldb:file:$${catalina.base}/platformHSQLDB.bin
      EIP_SAMPLE_DATABASE_USERNAME: platformUser
      EIP_SAMPLE_DATABASE_PASSWORD: platformUserPwd
    image: com.qpark.eip/sample:4.0.1
    restart: unless-stopped
    tty: true
    ports: 
      - "18080:8080"
      - "18010:8010"
      - "11099:1099"
