name: Java CI

on: [push]

jobs:
#  build_java_8:
#
#    runs-on: ubuntu-latest
#
#    steps:
#    - uses: actions/checkout@v1
#    - name: Set up JDK 8
#      uses: actions/setup-java@v1
#      with:
#        java-version: 8
#    - name: Build bom with Maven
#      run: mvn -B clean install --file pom.xml -P bom
#    - name: Build with Maven
#      run: mvn -B clean install --file pom.xml -P platform,impl,sample

  build_java_11:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    - name: Set up JDK 11
      uses: actions/setup-java@v1
      with:
        java-version: 11
    - name: Build bom with Maven
      run: mvn -B clean install --file pom.xml -P bom
    - name: Build with Maven
      run: mvn -B clean install --file pom.xml -P platform,impl,sample
