//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.11 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2016.09.15 at 03:50:39 PM CEST 
//


package com.qpark.eip.service.domain.doc.msg;

import javax.xml.bind.JAXBElement;
import javax.xml.bind.annotation.XmlElementDecl;
import javax.xml.bind.annotation.XmlRegistry;
import javax.xml.namespace.QName;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the com.qpark.eip.service.domain.doc.msg package. 
 * <p>An ObjectFactory allows you to programatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {

    private final static QName _GetRevisionRequest_QNAME = new QName("http://www.qpark-consulting.com/EIP/Utility/DocumentationModelServiceMessages-1.0", "GetRevisionRequest");
    private final static QName _GetRevisionResponse_QNAME = new QName("http://www.qpark-consulting.com/EIP/Utility/DocumentationModelServiceMessages-1.0", "GetRevisionResponse");
    private final static QName _GetServiceIdRequest_QNAME = new QName("http://www.qpark-consulting.com/EIP/Utility/DocumentationModelServiceMessages-1.0", "GetServiceIdRequest");
    private final static QName _GetServiceIdResponse_QNAME = new QName("http://www.qpark-consulting.com/EIP/Utility/DocumentationModelServiceMessages-1.0", "GetServiceIdResponse");
    private final static QName _GetServiceRequest_QNAME = new QName("http://www.qpark-consulting.com/EIP/Utility/DocumentationModelServiceMessages-1.0", "GetServiceRequest");
    private final static QName _GetServiceResponse_QNAME = new QName("http://www.qpark-consulting.com/EIP/Utility/DocumentationModelServiceMessages-1.0", "GetServiceResponse");
    private final static QName _GetElementTypeRequest_QNAME = new QName("http://www.qpark-consulting.com/EIP/Utility/DocumentationModelServiceMessages-1.0", "GetElementTypeRequest");
    private final static QName _GetElementTypeResponse_QNAME = new QName("http://www.qpark-consulting.com/EIP/Utility/DocumentationModelServiceMessages-1.0", "GetElementTypeResponse");
    private final static QName _GetDataTypeRequest_QNAME = new QName("http://www.qpark-consulting.com/EIP/Utility/DocumentationModelServiceMessages-1.0", "GetDataTypeRequest");
    private final static QName _GetDataTypeResponse_QNAME = new QName("http://www.qpark-consulting.com/EIP/Utility/DocumentationModelServiceMessages-1.0", "GetDataTypeResponse");
    private final static QName _GetTargetNamespaceRequest_QNAME = new QName("http://www.qpark-consulting.com/EIP/Utility/DocumentationModelServiceMessages-1.0", "GetTargetNamespaceRequest");
    private final static QName _GetTargetNamespaceResponse_QNAME = new QName("http://www.qpark-consulting.com/EIP/Utility/DocumentationModelServiceMessages-1.0", "GetTargetNamespaceResponse");
    private final static QName _GetClusterRequest_QNAME = new QName("http://www.qpark-consulting.com/EIP/Utility/DocumentationModelServiceMessages-1.0", "GetClusterRequest");
    private final static QName _GetClusterResponse_QNAME = new QName("http://www.qpark-consulting.com/EIP/Utility/DocumentationModelServiceMessages-1.0", "GetClusterResponse");
    private final static QName _GetComplexTypeRequest_QNAME = new QName("http://www.qpark-consulting.com/EIP/Utility/DocumentationModelServiceMessages-1.0", "GetComplexTypeRequest");
    private final static QName _GetComplexTypeResponse_QNAME = new QName("http://www.qpark-consulting.com/EIP/Utility/DocumentationModelServiceMessages-1.0", "GetComplexTypeResponse");
    private final static QName _GetFlowRequest_QNAME = new QName("http://www.qpark-consulting.com/EIP/Utility/DocumentationModelServiceMessages-1.0", "GetFlowRequest");
    private final static QName _GetFlowResponse_QNAME = new QName("http://www.qpark-consulting.com/EIP/Utility/DocumentationModelServiceMessages-1.0", "GetFlowResponse");
    private final static QName _GetFlowInterfaceMappingTypeRequest_QNAME = new QName("http://www.qpark-consulting.com/EIP/Utility/DocumentationModelServiceMessages-1.0", "GetFlowInterfaceMappingTypeRequest");
    private final static QName _GetFlowInterfaceMappingTypeResponse_QNAME = new QName("http://www.qpark-consulting.com/EIP/Utility/DocumentationModelServiceMessages-1.0", "GetFlowInterfaceMappingTypeResponse");
    private final static QName _GetFieldMappingTypeRequest_QNAME = new QName("http://www.qpark-consulting.com/EIP/Utility/DocumentationModelServiceMessages-1.0", "GetFieldMappingTypeRequest");
    private final static QName _GetFieldMappingTypeResponse_QNAME = new QName("http://www.qpark-consulting.com/EIP/Utility/DocumentationModelServiceMessages-1.0", "GetFieldMappingTypeResponse");

    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: com.qpark.eip.service.domain.doc.msg
     * 
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link GetServiceIdRequestType }
     * 
     */
    public GetServiceIdRequestType createGetServiceIdRequestType() {
        return new GetServiceIdRequestType();
    }

    /**
     * Create an instance of {@link GetServiceIdResponseType }
     * 
     */
    public GetServiceIdResponseType createGetServiceIdResponseType() {
        return new GetServiceIdResponseType();
    }

    /**
     * Create an instance of {@link GetRevisionRequestType }
     * 
     */
    public GetRevisionRequestType createGetRevisionRequestType() {
        return new GetRevisionRequestType();
    }

    /**
     * Create an instance of {@link GetRevisionResponseType }
     * 
     */
    public GetRevisionResponseType createGetRevisionResponseType() {
        return new GetRevisionResponseType();
    }

    /**
     * Create an instance of {@link GetServiceRequestType }
     * 
     */
    public GetServiceRequestType createGetServiceRequestType() {
        return new GetServiceRequestType();
    }

    /**
     * Create an instance of {@link GetServiceResponseType }
     * 
     */
    public GetServiceResponseType createGetServiceResponseType() {
        return new GetServiceResponseType();
    }

    /**
     * Create an instance of {@link GetElementTypeRequestType }
     * 
     */
    public GetElementTypeRequestType createGetElementTypeRequestType() {
        return new GetElementTypeRequestType();
    }

    /**
     * Create an instance of {@link GetElementTypeResponseType }
     * 
     */
    public GetElementTypeResponseType createGetElementTypeResponseType() {
        return new GetElementTypeResponseType();
    }

    /**
     * Create an instance of {@link GetDataTypeRequestType }
     * 
     */
    public GetDataTypeRequestType createGetDataTypeRequestType() {
        return new GetDataTypeRequestType();
    }

    /**
     * Create an instance of {@link GetDataTypeResponseType }
     * 
     */
    public GetDataTypeResponseType createGetDataTypeResponseType() {
        return new GetDataTypeResponseType();
    }

    /**
     * Create an instance of {@link GetTargetNamespaceRequestType }
     * 
     */
    public GetTargetNamespaceRequestType createGetTargetNamespaceRequestType() {
        return new GetTargetNamespaceRequestType();
    }

    /**
     * Create an instance of {@link GetTargetNamespaceResponseType }
     * 
     */
    public GetTargetNamespaceResponseType createGetTargetNamespaceResponseType() {
        return new GetTargetNamespaceResponseType();
    }

    /**
     * Create an instance of {@link GetClusterRequestType }
     * 
     */
    public GetClusterRequestType createGetClusterRequestType() {
        return new GetClusterRequestType();
    }

    /**
     * Create an instance of {@link GetClusterResponseType }
     * 
     */
    public GetClusterResponseType createGetClusterResponseType() {
        return new GetClusterResponseType();
    }

    /**
     * Create an instance of {@link GetComplexTypeRequestType }
     * 
     */
    public GetComplexTypeRequestType createGetComplexTypeRequestType() {
        return new GetComplexTypeRequestType();
    }

    /**
     * Create an instance of {@link GetComplexTypeResponseType }
     * 
     */
    public GetComplexTypeResponseType createGetComplexTypeResponseType() {
        return new GetComplexTypeResponseType();
    }

    /**
     * Create an instance of {@link GetFlowRequestType }
     * 
     */
    public GetFlowRequestType createGetFlowRequestType() {
        return new GetFlowRequestType();
    }

    /**
     * Create an instance of {@link GetFlowResponseType }
     * 
     */
    public GetFlowResponseType createGetFlowResponseType() {
        return new GetFlowResponseType();
    }

    /**
     * Create an instance of {@link GetFlowInterfaceMappingTypeRequestType }
     * 
     */
    public GetFlowInterfaceMappingTypeRequestType createGetFlowInterfaceMappingTypeRequestType() {
        return new GetFlowInterfaceMappingTypeRequestType();
    }

    /**
     * Create an instance of {@link GetFlowInterfaceMappingTypeResponseType }
     * 
     */
    public GetFlowInterfaceMappingTypeResponseType createGetFlowInterfaceMappingTypeResponseType() {
        return new GetFlowInterfaceMappingTypeResponseType();
    }

    /**
     * Create an instance of {@link GetFieldMappingTypeRequestType }
     * 
     */
    public GetFieldMappingTypeRequestType createGetFieldMappingTypeRequestType() {
        return new GetFieldMappingTypeRequestType();
    }

    /**
     * Create an instance of {@link GetFieldMappingTypeResponseType }
     * 
     */
    public GetFieldMappingTypeResponseType createGetFieldMappingTypeResponseType() {
        return new GetFieldMappingTypeResponseType();
    }

    /**
     * Create an instance of {@link RequestMessage }
     * 
     */
    public RequestMessage createRequestMessage() {
        return new RequestMessage();
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link GetServiceIdRequestType }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.qpark-consulting.com/EIP/Utility/DocumentationModelServiceMessages-1.0", name = "GetServiceIdRequest")
    public JAXBElement<GetServiceIdRequestType> createGetServiceIdRequest(GetServiceIdRequestType value) {
        return new JAXBElement<GetServiceIdRequestType>(_GetServiceIdRequest_QNAME, GetServiceIdRequestType.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link GetServiceIdResponseType }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.qpark-consulting.com/EIP/Utility/DocumentationModelServiceMessages-1.0", name = "GetServiceIdResponse")
    public JAXBElement<GetServiceIdResponseType> createGetServiceIdResponse(GetServiceIdResponseType value) {
        return new JAXBElement<GetServiceIdResponseType>(_GetServiceIdResponse_QNAME, GetServiceIdResponseType.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link GetRevisionRequestType }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.qpark-consulting.com/EIP/Utility/DocumentationModelServiceMessages-1.0", name = "GetRevisionRequest")
    public JAXBElement<GetRevisionRequestType> createGetRevisionRequest(GetRevisionRequestType value) {
        return new JAXBElement<GetRevisionRequestType>(_GetRevisionRequest_QNAME, GetRevisionRequestType.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link GetRevisionResponseType }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.qpark-consulting.com/EIP/Utility/DocumentationModelServiceMessages-1.0", name = "GetRevisionResponse")
    public JAXBElement<GetRevisionResponseType> createGetRevisionResponse(GetRevisionResponseType value) {
        return new JAXBElement<GetRevisionResponseType>(_GetRevisionResponse_QNAME, GetRevisionResponseType.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link GetServiceRequestType }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.qpark-consulting.com/EIP/Utility/DocumentationModelServiceMessages-1.0", name = "GetServiceRequest")
    public JAXBElement<GetServiceRequestType> createGetServiceRequest(GetServiceRequestType value) {
        return new JAXBElement<GetServiceRequestType>(_GetServiceRequest_QNAME, GetServiceRequestType.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link GetServiceResponseType }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.qpark-consulting.com/EIP/Utility/DocumentationModelServiceMessages-1.0", name = "GetServiceResponse")
    public JAXBElement<GetServiceResponseType> createGetServiceResponse(GetServiceResponseType value) {
        return new JAXBElement<GetServiceResponseType>(_GetServiceResponse_QNAME, GetServiceResponseType.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link GetElementTypeRequestType }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.qpark-consulting.com/EIP/Utility/DocumentationModelServiceMessages-1.0", name = "GetElementTypeRequest")
    public JAXBElement<GetElementTypeRequestType> createGetElementTypeRequest(GetElementTypeRequestType value) {
        return new JAXBElement<GetElementTypeRequestType>(_GetElementTypeRequest_QNAME, GetElementTypeRequestType.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link GetElementTypeResponseType }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.qpark-consulting.com/EIP/Utility/DocumentationModelServiceMessages-1.0", name = "GetElementTypeResponse")
    public JAXBElement<GetElementTypeResponseType> createGetElementTypeResponse(GetElementTypeResponseType value) {
        return new JAXBElement<GetElementTypeResponseType>(_GetElementTypeResponse_QNAME, GetElementTypeResponseType.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link GetDataTypeRequestType }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.qpark-consulting.com/EIP/Utility/DocumentationModelServiceMessages-1.0", name = "GetDataTypeRequest")
    public JAXBElement<GetDataTypeRequestType> createGetDataTypeRequest(GetDataTypeRequestType value) {
        return new JAXBElement<GetDataTypeRequestType>(_GetDataTypeRequest_QNAME, GetDataTypeRequestType.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link GetDataTypeResponseType }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.qpark-consulting.com/EIP/Utility/DocumentationModelServiceMessages-1.0", name = "GetDataTypeResponse")
    public JAXBElement<GetDataTypeResponseType> createGetDataTypeResponse(GetDataTypeResponseType value) {
        return new JAXBElement<GetDataTypeResponseType>(_GetDataTypeResponse_QNAME, GetDataTypeResponseType.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link GetTargetNamespaceRequestType }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.qpark-consulting.com/EIP/Utility/DocumentationModelServiceMessages-1.0", name = "GetTargetNamespaceRequest")
    public JAXBElement<GetTargetNamespaceRequestType> createGetTargetNamespaceRequest(GetTargetNamespaceRequestType value) {
        return new JAXBElement<GetTargetNamespaceRequestType>(_GetTargetNamespaceRequest_QNAME, GetTargetNamespaceRequestType.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link GetTargetNamespaceResponseType }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.qpark-consulting.com/EIP/Utility/DocumentationModelServiceMessages-1.0", name = "GetTargetNamespaceResponse")
    public JAXBElement<GetTargetNamespaceResponseType> createGetTargetNamespaceResponse(GetTargetNamespaceResponseType value) {
        return new JAXBElement<GetTargetNamespaceResponseType>(_GetTargetNamespaceResponse_QNAME, GetTargetNamespaceResponseType.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link GetClusterRequestType }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.qpark-consulting.com/EIP/Utility/DocumentationModelServiceMessages-1.0", name = "GetClusterRequest")
    public JAXBElement<GetClusterRequestType> createGetClusterRequest(GetClusterRequestType value) {
        return new JAXBElement<GetClusterRequestType>(_GetClusterRequest_QNAME, GetClusterRequestType.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link GetClusterResponseType }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.qpark-consulting.com/EIP/Utility/DocumentationModelServiceMessages-1.0", name = "GetClusterResponse")
    public JAXBElement<GetClusterResponseType> createGetClusterResponse(GetClusterResponseType value) {
        return new JAXBElement<GetClusterResponseType>(_GetClusterResponse_QNAME, GetClusterResponseType.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link GetComplexTypeRequestType }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.qpark-consulting.com/EIP/Utility/DocumentationModelServiceMessages-1.0", name = "GetComplexTypeRequest")
    public JAXBElement<GetComplexTypeRequestType> createGetComplexTypeRequest(GetComplexTypeRequestType value) {
        return new JAXBElement<GetComplexTypeRequestType>(_GetComplexTypeRequest_QNAME, GetComplexTypeRequestType.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link GetComplexTypeResponseType }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.qpark-consulting.com/EIP/Utility/DocumentationModelServiceMessages-1.0", name = "GetComplexTypeResponse")
    public JAXBElement<GetComplexTypeResponseType> createGetComplexTypeResponse(GetComplexTypeResponseType value) {
        return new JAXBElement<GetComplexTypeResponseType>(_GetComplexTypeResponse_QNAME, GetComplexTypeResponseType.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link GetFlowRequestType }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.qpark-consulting.com/EIP/Utility/DocumentationModelServiceMessages-1.0", name = "GetFlowRequest")
    public JAXBElement<GetFlowRequestType> createGetFlowRequest(GetFlowRequestType value) {
        return new JAXBElement<GetFlowRequestType>(_GetFlowRequest_QNAME, GetFlowRequestType.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link GetFlowResponseType }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.qpark-consulting.com/EIP/Utility/DocumentationModelServiceMessages-1.0", name = "GetFlowResponse")
    public JAXBElement<GetFlowResponseType> createGetFlowResponse(GetFlowResponseType value) {
        return new JAXBElement<GetFlowResponseType>(_GetFlowResponse_QNAME, GetFlowResponseType.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link GetFlowInterfaceMappingTypeRequestType }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.qpark-consulting.com/EIP/Utility/DocumentationModelServiceMessages-1.0", name = "GetFlowInterfaceMappingTypeRequest")
    public JAXBElement<GetFlowInterfaceMappingTypeRequestType> createGetFlowInterfaceMappingTypeRequest(GetFlowInterfaceMappingTypeRequestType value) {
        return new JAXBElement<GetFlowInterfaceMappingTypeRequestType>(_GetFlowInterfaceMappingTypeRequest_QNAME, GetFlowInterfaceMappingTypeRequestType.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link GetFlowInterfaceMappingTypeResponseType }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.qpark-consulting.com/EIP/Utility/DocumentationModelServiceMessages-1.0", name = "GetFlowInterfaceMappingTypeResponse")
    public JAXBElement<GetFlowInterfaceMappingTypeResponseType> createGetFlowInterfaceMappingTypeResponse(GetFlowInterfaceMappingTypeResponseType value) {
        return new JAXBElement<GetFlowInterfaceMappingTypeResponseType>(_GetFlowInterfaceMappingTypeResponse_QNAME, GetFlowInterfaceMappingTypeResponseType.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link GetFieldMappingTypeRequestType }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.qpark-consulting.com/EIP/Utility/DocumentationModelServiceMessages-1.0", name = "GetFieldMappingTypeRequest")
    public JAXBElement<GetFieldMappingTypeRequestType> createGetFieldMappingTypeRequest(GetFieldMappingTypeRequestType value) {
        return new JAXBElement<GetFieldMappingTypeRequestType>(_GetFieldMappingTypeRequest_QNAME, GetFieldMappingTypeRequestType.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link GetFieldMappingTypeResponseType }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.qpark-consulting.com/EIP/Utility/DocumentationModelServiceMessages-1.0", name = "GetFieldMappingTypeResponse")
    public JAXBElement<GetFieldMappingTypeResponseType> createGetFieldMappingTypeResponse(GetFieldMappingTypeResponseType value) {
        return new JAXBElement<GetFieldMappingTypeResponseType>(_GetFieldMappingTypeResponse_QNAME, GetFieldMappingTypeResponseType.class, null, value);
    }

}
