//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.11 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2016.09.15 at 03:50:39 PM CEST 
//

@javax.xml.bind.annotation.XmlSchema(namespace = "http://www.qpark-consulting.com/EIP/Utility/DocumentationModelServiceMessages-1.0")
package com.qpark.eip.service.domain.doc.msg;
